//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BICYCLETUBEUSAGE
    {
        public int SERIALNUMBER { get; set; }
        public int TUBEID { get; set; }
        public Nullable<int> QUANTITY { get; set; }
    
        public virtual BICYCLE BICYCLE { get; set; }
        public virtual TUBEMATERIAL TUBEMATERIAL { get; set; }
    }
}
