//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BikeShopEntities : DbContext
    {
        public BikeShopEntities()
            : base("name=BikeShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BICYCLE> BICYCLEs { get; set; }
        public virtual DbSet<BICYCLETUBEUSAGE> BICYCLETUBEUSAGEs { get; set; }
        public virtual DbSet<BIKEPART> BIKEPARTS { get; set; }
        public virtual DbSet<BIKETUBE> BIKETUBES { get; set; }
        public virtual DbSet<CITY> CITies { get; set; }
        public virtual DbSet<COMMONSIZE> COMMONSIZES { get; set; }
        public virtual DbSet<COMPONENT> COMPONENTs { get; set; }
        public virtual DbSet<COMPONENTNAME> COMPONENTNAMEs { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<CUSTOMERTRANSACTION> CUSTOMERTRANSACTIONs { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual DbSet<GROUPO> GROUPOes { get; set; }
        public virtual DbSet<LETTERSTYLE> LETTERSTYLEs { get; set; }
        public virtual DbSet<MANUFACTURER> MANUFACTURERs { get; set; }
        public virtual DbSet<MANUFACTURERTRANSACTION> MANUFACTURERTRANSACTIONs { get; set; }
        public virtual DbSet<MODELSIZE> MODELSIZEs { get; set; }
        public virtual DbSet<MODELTYPE> MODELTYPEs { get; set; }
        public virtual DbSet<PAINT> PAINTs { get; set; }
        public virtual DbSet<PREFERENCE> PREFERENCEs { get; set; }
        public virtual DbSet<PURCHASEITEM> PURCHASEITEMs { get; set; }
        public virtual DbSet<PURCHASEORDER> PURCHASEORDERs { get; set; }
        public virtual DbSet<RETAILSTORE> RETAILSTOREs { get; set; }
        public virtual DbSet<REVISIONHISTORY> REVISIONHISTORies { get; set; }
        public virtual DbSet<SAMPLENAME> SAMPLENAMEs { get; set; }
        public virtual DbSet<SAMPLESTREET> SAMPLESTREETs { get; set; }
        public virtual DbSet<STATETAXRATE> STATETAXRATEs { get; set; }
        public virtual DbSet<TEMPDATEMADE> TEMPDATEMADEs { get; set; }
        public virtual DbSet<TUBEMATERIAL> TUBEMATERIALs { get; set; }
        public virtual DbSet<WORKAREA> WORKAREAs { get; set; }
        public virtual DbSet<LoginAttempt> LoginAttempts { get; set; }
    }
}
