//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIKEPART
    {
        public int SERIALNUMBER { get; set; }
        public int COMPONENTID { get; set; }
        public Nullable<int> SUBSTITUTEID { get; set; }
        public string LOCATION { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<System.DateTime> DATEINSTALLED { get; set; }
        public Nullable<int> EMPLOYEEID { get; set; }
    
        public virtual BICYCLE BICYCLE { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual COMPONENT COMPONENT { get; set; }
    }
}
