//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CITY()
        {
            this.CUSTOMERs = new HashSet<CUSTOMER>();
            this.EMPLOYEEs = new HashSet<EMPLOYEE>();
            this.MANUFACTURERs = new HashSet<MANUFACTURER>();
            this.RETAILSTOREs = new HashSet<RETAILSTORE>();
        }
    
        public int CITYID { get; set; }
        public string ZIPCODE { get; set; }
        public string CITY1 { get; set; }
        public string STATE { get; set; }
        public string AREACODE { get; set; }
        public Nullable<int> POPULATION1990 { get; set; }
        public Nullable<int> POPULATION1980 { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<int> LATITUDE { get; set; }
        public Nullable<int> LONGITUDE { get; set; }
        public Nullable<int> POPULATIONCDF { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER> CUSTOMERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE> EMPLOYEEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANUFACTURER> MANUFACTURERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETAILSTORE> RETAILSTOREs { get; set; }
    }
}
