//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMONSIZE
    {
        public string MODELTYPE { get; set; }
        public int FRAMESIZE { get; set; }
    }
}
