//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPONENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPONENT()
        {
            this.BIKEPARTS = new HashSet<BIKEPART>();
            this.PURCHASEITEMs = new HashSet<PURCHASEITEM>();
            this.GROUPOes = new HashSet<GROUPO>();
        }
    
        public int COMPONENTID { get; set; }
        public Nullable<int> MANUFACTURERID { get; set; }
        public string PRODUCTNUMBER { get; set; }
        public string ROAD { get; set; }
        public string CATEGORY { get; set; }
        public Nullable<int> LENGTH { get; set; }
        public Nullable<int> HEIGHT { get; set; }
        public Nullable<int> WIDTH { get; set; }
        public Nullable<int> WEIGHT { get; set; }
        public Nullable<int> YEAR { get; set; }
        public Nullable<int> ENDYEAR { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> LISTPRICE { get; set; }
        public Nullable<decimal> ESTIMATEDCOST { get; set; }
        public Nullable<int> QUANTITYONHAND { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIKEPART> BIKEPARTS { get; set; }
        public virtual COMPONENTNAME COMPONENTNAME { get; set; }
        public virtual MANUFACTURER MANUFACTURER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PURCHASEITEM> PURCHASEITEMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROUPO> GROUPOes { get; set; }
    }
}
