//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.BICYCLEs = new HashSet<BICYCLE>();
            this.BIKEPARTS = new HashSet<BIKEPART>();
            this.PURCHASEORDERs = new HashSet<PURCHASEORDER>();
        }
    
        public int EMPLOYEEID { get; set; }
        public string TAXPAYERID { get; set; }
        public string LASTNAME { get; set; }
        public string FIRSTNAME { get; set; }
        public string HOMEPHONE { get; set; }
        public string ADDRESS { get; set; }
        public string ZIPCODE { get; set; }
        public Nullable<int> CITYID { get; set; }
        public Nullable<System.DateTime> DATEHIRED { get; set; }
        public Nullable<System.DateTime> DATERELEASED { get; set; }
        public Nullable<int> CURRENTMANAGER { get; set; }
        public Nullable<int> SALARYGRADE { get; set; }
        public Nullable<decimal> SALARY { get; set; }
        public string TITLE { get; set; }
        public string WORKAREA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BICYCLE> BICYCLEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIKEPART> BIKEPARTS { get; set; }
        public virtual CITY CITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PURCHASEORDER> PURCHASEORDERs { get; set; }
    }
}
