//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GROUPO()
        {
            this.COMPONENTs = new HashSet<COMPONENT>();
        }
    
        public int COMPONENTGROUPID { get; set; }
        public string GROUPNAME { get; set; }
        public string BIKETYPE { get; set; }
        public Nullable<int> YEAR { get; set; }
        public Nullable<int> ENDYEAR { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPONENT> COMPONENTs { get; set; }
    }
}
