//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODELSIZE
    {
        public string MODELTYPE { get; set; }
        public int MSIZE { get; set; }
        public Nullable<int> TOPTUBE { get; set; }
        public Nullable<int> CHAINSTAY { get; set; }
        public Nullable<int> TOTALLENGTH { get; set; }
        public Nullable<int> GROUNDCLEARANCE { get; set; }
        public Nullable<int> HEADTUBEANGLE { get; set; }
        public Nullable<int> SEATTUBEANGLE { get; set; }
    
        public virtual MODELTYPE MODELTYPE1 { get; set; }
    }
}
