//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAINT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAINT()
        {
            this.BICYCLEs = new HashSet<BICYCLE>();
        }
    
        public int PAINTID { get; set; }
        public string COLORNAME { get; set; }
        public string COLORSTYLE { get; set; }
        public string COLORLIST { get; set; }
        public Nullable<System.DateTime> DATEINTRODUCED { get; set; }
        public Nullable<System.DateTime> DATEDISCONTINUED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BICYCLE> BICYCLEs { get; set; }
    }
}
