//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREFERENCE
    {
        public string ITEMNAME { get; set; }
        public Nullable<int> VALUE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> DATECHANGED { get; set; }
    }
}
