//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURCHASEORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PURCHASEORDER()
        {
            this.PURCHASEITEMs = new HashSet<PURCHASEITEM>();
        }
    
        public int PURCHASEID { get; set; }
        public Nullable<int> EMPLOYEEID { get; set; }
        public Nullable<int> MANUFACTURERID { get; set; }
        public Nullable<decimal> TOTALLIST { get; set; }
        public Nullable<decimal> SHIPPINGCOST { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<System.DateTime> ORDERDATE { get; set; }
        public Nullable<System.DateTime> RECEIVEDATE { get; set; }
        public Nullable<decimal> AMOUNTDUE { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual MANUFACTURER MANUFACTURER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PURCHASEITEM> PURCHASEITEMs { get; set; }
    }
}
