//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUBEMATERIAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUBEMATERIAL()
        {
            this.BICYCLETUBEUSAGEs = new HashSet<BICYCLETUBEUSAGE>();
            this.BIKETUBES = new HashSet<BIKETUBE>();
        }
    
        public int TUBEID { get; set; }
        public string MATERIAL { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> DIAMETER { get; set; }
        public Nullable<int> THICKNESS { get; set; }
        public string ROUNDNESS { get; set; }
        public Nullable<int> WEIGHT { get; set; }
        public Nullable<int> STIFFNESS { get; set; }
        public Nullable<decimal> LISTPRICE { get; set; }
        public string CONSTRUCTION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BICYCLETUBEUSAGE> BICYCLETUBEUSAGEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIKETUBE> BIKETUBES { get; set; }
    }
}
